In [1]:
import pandas as pd

In [55]:
ds_salaries = pd.read_csv("./data/DataScience_salaries_2025.csv", usecols = ["work_year", "experience_level", "job_title", "salary_in_usd","company_location", "company_size" ])

In [57]:
ds_salaries

,work_year,experience_level,job_title,salary_in_usd,company_location,company_size
0,2025,MI,Research Scientist,208000,US,M
1,2025,MI,Research Scientist,147000,US,M
2,2025,SE,Research Scientist,173000,US,M
3,2025,SE,Research Scientist,117000,US,M
4,2025,MI,AI Engineer,100000,US,M
...,...,...,...,...,...,...
93592,2020,SE,Data Scientist,412000,US,L
93593,2021,MI,Principal Data Scientist,151000,US,L
93594,2020,EN,Data Scientist,105000,US,S
93595,2020,EN,Business Data Analyst,100000,US,L
93596,2021,SE,Data Scientist,94665,IN,L

In [97]:
ds_salaries.monthly_salary = ds_salaries.monthly_salary.round(2)

In [103]:
ds_salaries

,work_year,experience_level,job_title,salary_in_usd,monthly_salary,company_location,company_size
0,2025,MI,Research Scientist,208000,17333.33,US,M
1,2025,MI,Research Scientist,147000,12250.00,US,M
2,2025,SE,Research Scientist,173000,14416.67,US,M
3,2025,SE,Research Scientist,117000,9750.00,US,M
4,2025,MI,AI Engineer,100000,8333.33,US,M
...,...,...,...,...,...,...,...
93592,2020,SE,Data Scientist,412000,34333.33,US,L
93593,2021,MI,Principal Data Scientist,151000,12583.33,US,L
93594,2020,EN,Data Scientist,105000,8750.00,US,S
93595,2020,EN,Business Data Analyst,100000,8333.33,US,L
93596,2021,SE,Data Scientist,94665,7888.75,IN,L

In [109]:
ds_salaries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93597 entries, 0 to 93596
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   work_year         93597 non-null  int64
 1   experience_level  93597 non-null  object
 2   job_title         93597 non-null  object
 3   salary_in_usd     93597 non-null  int64
 4   monthly_salary    93597 non-null  float64
 5   company_location  93597 non-null  object
 6   company_size      93597 non-null  object
dtypes: float64(1), int64(2), object(4)
memory usage: 5.0+ MB

In [117]:
mean_salary = ds_salaries.monthly_salary.mean().round(2)
mean_salary

13128.97

In [129]:
min_salary = ds_salaries.monthly_salary.min()
min_salary

1250.0

In [135]:
max_salary = ds_salaries.monthly_salary.max()
max_salary

66666.67

In [141]:
ds_salaries.company_location.value_counts()

company_location
US    84347
CA     3416
GB     2670
AU      317
DE      282
      ...
MU        1
GI        1
OM        1
ZM        1
MD        1
Name: count, Length: 90, dtype: int64

In [169]:
ds_pol = ds_salaries.query("company_location == 'PL'")
ds_us = ds_salaries.query("company_location == 'US'")

In [184]:
us_mean_salary = ds_us.salary_in_usd.mean().round(2)
pol_mean_salary = ds_pol.salary_in_usd.mean().round(2)

print("Mean salary in USA: {}, mean salary in Poland: {}".format(us_mean_salary, pol_mean_salary))

Mean salary in USA: 163452.12, mean salary in Poland: 78797.66

In [196]:
percentage = round((us_mean_salary - pol_mean_salary)/pol_mean_salary * 100,2)

In [198]:
print("{}%".format(percentage))

107.43%